version: "3"
services:
    db:
        image: postgres:9.4
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: prueba
    redis:
        image: redis
        command: redis-server
        ports: 
            - "6379:6379"
        volumes:
            - redis:/var/lib/redis/data
volumes:
    postgres:
    redis: